# fly.toml app configuration file generated for stock-watchlist-noble-leaf-2877 on 2026-07-23T15:58:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stock-watchlist-noble-leaf-2877'
primary_region = 'iad'

[build]
[env]
  AWS_REGION = 'us-east-1'
  COOKIE_SECURE = '1'
  DATA_DIR = '/data'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8088
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1024mb'
